# -*- coding: utf-8 -*-
"""Clasificador bayesiano-Predicción de sentencia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1COIe0cQG8_Sr1Fv8VFYNB1pUWmi3d57P
"""

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

# Dataset
training_data = [
    ('Me encanta esta pelicula!', 'Positivo'),
    ('No me gusta esta pelicula!', 'Negativo'),
    ('Esta pelicula es mala!', 'Negativo'),
    ('La actuacion es genia;!', 'Positivo'),
    ('La trama es confusa.', 'Negativo'),
    ('Los efectos especiales son buenisimos!', 'Positivo'),
]

vectorizer = CountVectorizer()
features = vectorizer.fit_transform([data[0] for data in training_data])

# Definir etiqueta objetivo
labels = [data[1] for data in training_data]

X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2)

# Entrenamiento
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

accuracy = classifier.score(X_test, y_test)
print('precision:', accuracy)

# Prediccion de sentencia
new_sentence = 'Esta pelicula es confusa'
new_features = vectorizer.transform([new_sentence])
predicted_label = classifier.predict(new_features)[0]
print('Sentimiento predecido:', predicted_label)
